# Generated by Django 4.2 on 2024-11-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_subscription_delete_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date_subscribed',
        ),
        migrations.AddField(
            model_name='subscription',
            name='confirmation_code',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
