# Generated by Django 4.2 on 2024-11-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_subscription_date_subscribed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
