# Generated by Django 4.2 on 2024-11-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address2',
            field=models.CharField(default='test sample data', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_state',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_zipcode',
            field=models.CharField(default='abcd', max_length=200),
            preserve_default=False,
        ),
    ]
