# Generated by Django 4.2 on 2024-11-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_supplier_supplier_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_company_name',
            field=models.CharField(default='abcdef', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
