# Generated by Django 4.2 on 2024-11-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_supplier_supplier_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
