# Generated by Django 4.2 on 2024-11-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymentofpaypal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_email',
        ),
    ]
