# Generated by Django 4.2 on 2024-12-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_shippingaddress_shipping_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentofpaypal',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
