# Generated by Django 4.2 on 2024-11-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_supplier_supplier_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='store.product'),
        ),
    ]
