# Generated by Django 4.2 on 2024-11-10 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0008_delete_paymentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOfPayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=19)),
                ('card_exp_date', models.CharField(max_length=5)),
                ('card_cvv_number', models.CharField(max_length=4)),
                ('card_address1', models.CharField(max_length=200)),
                ('card_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('card_city', models.CharField(max_length=200)),
                ('card_state', models.CharField(max_length=200)),
                ('card_zipcode', models.CharField(max_length=200)),
                ('card_country', models.CharField(max_length=200)),
                ('user_paypal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment PayPal',
            },
        ),
    ]
